# Generated by Django 3.1.3 on 2020-11-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='名前')),
                ('hp', models.IntegerField(default=0, verbose_name='HP')),
                ('attack', models.IntegerField(default=0, verbose_name='攻撃')),
                ('defence', models.IntegerField(default=0, verbose_name='防御')),
                ('counter', models.IntegerField(default=0, verbose_name='反撃')),
                ('move', models.IntegerField(default=1, verbose_name='移動')),
                ('range', models.IntegerField(default=1, verbose_name='攻撃距離')),
                ('site', models.IntegerField(default=1, verbose_name='視野')),
                ('text', models.CharField(default='普通のユニットです。', max_length=50, verbose_name='備考')),
                ('special1', models.CharField(blank=True, default='-', max_length=50, null=True, verbose_name='特殊1')),
                ('special2', models.CharField(blank=True, default='-', max_length=50, null=True, verbose_name='特殊2')),
                ('special3', models.CharField(blank=True, default='-', max_length=50, null=True, verbose_name='特殊3')),
                ('special4', models.CharField(blank=True, default='-', max_length=50, null=True, verbose_name='特殊4')),
            ],
        ),
    ]
